### ISSUE TITLE
error in airnotifier log

### ISSUE THREAD

**Issue by sweta484** [airnotifier/airnotifier#185] opened 2018-06-05 02:11 UTC
[I 180604 17:26:09 apns:190] APNs connection: swet[0] is online
Enter PEM pass phrase:
[E 180604 17:26:09 iostream:543] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/tornado/iostream.py", line 504, in _handle_events
        self._handle_connect()
      File "/usr/lib64/python2.7/site-packages/tornado/iostream.py", line 1359, in _handle_connect
        do_handshake_on_connect=False)
      File "/usr/lib64/python2.7/site-packages/tornado/netutil.py", line 501, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/usr/lib64/python2.7/site-packages/tornado/netutil.py", line 478, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    IOError: [Errno 22] Invalid argument
[E 180604 17:26:09 ioloop:612] Exception in callback None
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 866, in start
        handler_func(fd_obj, events)
      File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/lib64/python2.7/site-packages/tornado/iostream.py", line 504, in _handle_events
        self._handle_connect()
      File "/usr/lib64/python2.7/site-packages/tornado/iostream.py", line 1359, in _handle_connect
        do_handshake_on_connect=False)
      File "/usr/lib64/python2.7/site-packages/tornado/netutil.py", line 501, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/usr/lib64/python2.7/site-packages/tornado/netutil.py", line 478, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    IOError: [Errno 22] Invalid argument
[

**Comment by dcai** [comment] 2019-11-21 04:12
closing as I couldn't reproduce it anymore.

**Closed by dcai** 2019-11-21 04:12 UTC
